# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccmb" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "0aecd6ea79f1b1f099f202e89f784e58d8d65788040bb262b9bdfa4e19e73891"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_arm64.zip"
    end
    on_intel do
      sha256 "3031f94716b4b8ec192470cd6f6119fe527f5c3425630347f9823a68d81de398"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "7a35d5bd8a5d940c25d7219ac4a3db4414abcd04c6a80eb25c5d39e6414cc673"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_arm64.zip"
    end
    on_intel do
      sha256 "82cab097eefb5f207efbd7878d1669e53060af497bdc59a00581829c32cb180b"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_amd64.zip"
    end
  end

  name "ccmb"
  desc "Context Combiner (ccmb) is a command-line tool that flattens, filters, converts, and merges files."
  homepage "https://github.com/jonas-lesage-be/ccmb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccmb"

  # No zap stanza required
end
