# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccmb" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "6c02e51aac1ebb683df96cb954c9d134721129563ed9c215d8daa7bda5114a2a"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c2d45fd58f8ce3f9254f0f34a748127a7e6bb4590ce4e21bb6c1369d2e993dc"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cc72bb81e476e5689290fa7ef4498283432a7ca91dc72162682dabfece0188a6"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8361ec837f75d65bc94491bf3653c06ba5b6cd8a888d80ef3b2de32d0ce2d560"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccmb"
  desc "Context Combiner (ccmb) is a command-line tool that flattens, filters, converts, and merges files."
  homepage "https://github.com/jonas-lesage-be/ccmb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccmb"

  # No zap stanza required
end
