# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccmb" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a5935ba303e1a4ddd4444150681124e5d5cdcd21364b9f314d6cb73ec1edd5c7"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a83c113c61a4e280d2630a9ca2e158f1c9636bfcdae986f2c7780100ebc2050a"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b3799025173df805e3b559bd68a6b93c52f1c417a20ef52e178ed50a2f448771"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8563a4e7b48edfba0aab75a2fcb013e65cb66f7af65ae902d5e5b51ac6e3c2a6"
      url "https://github.com/jonas-lesage-be/ccmb/releases/download/v#{version}/ccmb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccmb"
  desc "Context Combiner (ccmb) is a command-line tool that flattens, filters, converts, and merges files."
  homepage "https://github.com/jonas-lesage-be/ccmb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccmb"

  # No zap stanza required
end
